/**
 * Declarative indicator descriptor data.
 *
 * Pure configuration — no logic. Each entry defines how one indicator
 * appears across charts, tables, cards, and the holdings grid.
 * Add new indicators here; helpers live in indicator-registry.ts.
 */

import type { IndicatorDescriptor } from "./indicator-registry"

export const INDICATOR_REGISTRY: IndicatorDescriptor[] = [
  {
    id: "rsi",
    label: "RSI (14)",
    shortLabel: "RSI",
    description: "Momentum oscillator (0–100). Above 70 = overbought, below 30 = oversold.",
    category: "technical",
    placement: "subchart",
    capabilities: ["group_table", "group_card", "detail_chart", "detail_card", "detail_stats"],
    defaults: ["group_table", "detail_chart"],
    fields: ["rsi", "rsi_delta", "rsi_delta_sigma"],
    sortableFields: ["rsi"],
    series: [
      {
        field: "rsi",
        label: "RSI",
        color: "#8b5cf6",
        lineWidth: 2,
        thresholdColors: [
          { condition: "gte", value: 70, className: "text-red-500" },
          { condition: "lte", value: 30, className: "text-emerald-500" },
        ],
      },
    ],
    decimals: 0,
    chartConfig: {
      lines: [
        { value: 70, color: "rgba(239, 68, 68, 0.5)" },
        { value: 30, color: "rgba(34, 197, 94, 0.5)" },
      ],
      range: { min: 0, max: 100 },
    },
    holdingSummary: { label: "RSI", field: "rsi", format: "numeric" },
    cardEligible: true,
  },
  {
    id: "sma_20",
    label: "SMA (20)",
    shortLabel: "SMA20",
    description: "20-day simple moving average — short-term trend direction.",
    category: "technical",
    placement: "overlay",
    capabilities: ["group_table", "group_card", "detail_chart", "detail_stats"],
    defaults: ["group_table", "detail_chart"],
    fields: ["sma_20"],
    sortableFields: [],
    series: [
      { field: "sma_20", label: "SMA 20", color: "#14b8a6", lineWidth: 1 },
    ],
    decimals: 2,
    holdingSummary: { label: "SMA20", field: "sma_20", format: "compare_close" },
  },
  {
    id: "sma_50",
    label: "SMA (50)",
    shortLabel: "SMA50",
    description: "50-day simple moving average — medium-term trend direction.",
    category: "technical",
    placement: "overlay",
    capabilities: ["group_table", "group_card", "detail_chart", "detail_stats"],
    defaults: ["group_table", "detail_chart"],
    fields: ["sma_50"],
    sortableFields: [],
    series: [
      { field: "sma_50", label: "SMA 50", color: "#8b5cf6", lineWidth: 1 },
    ],
    decimals: 2,
  },
  {
    id: "bb",
    label: "Bollinger Bands",
    shortLabel: "BB",
    description: "Volatility envelope around 20-day SMA. Price near bands signals potential reversal.",
    category: "technical",
    placement: "overlay",
    capabilities: ["group_table", "group_card", "detail_chart", "detail_stats"],
    defaults: ["group_table", "detail_chart"],
    fields: ["bb_upper", "bb_middle", "bb_lower"],
    sortableFields: [],
    series: [
      { field: "bb_upper", label: "BB Upper", color: "rgba(96, 165, 250, 0.4)", legendColor: "#60a5fa", lineWidth: 1 },
      { field: "bb_lower", label: "BB Lower", color: "rgba(96, 165, 250, 0.4)", legendColor: "#60a5fa", lineWidth: 1 },
    ],
    decimals: 2,
    bandFill: { upperField: "bb_upper", lowerField: "bb_lower" },
    holdingSummary: {
      label: "BB",
      field: "bb_position",
      format: "string_map",
      colorMap: { above: "text-red-500", below: "text-emerald-500" },
    },
  },
  {
    id: "macd",
    label: "MACD (12,26,9)",
    shortLabel: "MACD",
    description: "Trend and momentum indicator. Signal line crossovers indicate direction changes.",
    category: "technical",
    placement: "subchart",
    capabilities: ["group_table", "group_card", "detail_chart", "detail_card", "detail_stats"],
    defaults: ["group_table", "detail_chart"],
    fields: [
      "macd", "macd_signal", "macd_hist",
      "macd_hist_delta", "macd_hist_delta_sigma",
      "macd_delta", "macd_delta_sigma",
    ],
    sortableFields: ["macd"],
    series: [
      {
        field: "macd_hist",
        label: "Histogram",
        color: "",
        type: "histogram",
        thresholdColors: [
          { condition: "gte", value: 0, className: "text-emerald-400" },
          { condition: "lt", value: 0, className: "text-red-400" },
        ],
        histogramColors: { positive: "rgba(34, 197, 94, 0.6)", negative: "rgba(239, 68, 68, 0.6)" },
      },
      { field: "macd", label: "MACD", color: "#38bdf8", lineWidth: 2 },
      { field: "macd_signal", label: "Signal", color: "#fb923c", lineWidth: 2 },
    ],
    decimals: 2,
    chartConfig: {
      lines: [{ value: 0, color: "rgba(161, 161, 170, 0.3)" }],
    },
    holdingSummary: {
      label: "MACD",
      field: "macd_signal_dir",
      format: "string_map",
      colorMap: { bullish: "text-emerald-500", bearish: "text-red-500" },
    },
    cardEligible: true,
    snapField: "macd",
  },
  {
    id: "atr",
    label: "ATR (14)",
    shortLabel: "ATR",
    description: "Average True Range — absolute price volatility over 14 days.",
    category: "volatility",
    placement: "card",
    capabilities: ["group_table", "group_card", "detail_card", "detail_stats"],
    defaults: ["group_table", "detail_card"],
    fields: ["atr"],
    sortableFields: ["atr"],
    series: [
      { field: "atr", label: "ATR", color: "#f97316", lineWidth: 2 },
    ],
    decimals: 2,
    holdingSummary: { label: "ATR", field: "atr", format: "numeric" },
    priceDenominated: true,
  },
  {
    id: "atr_pct",
    label: "ATR%",
    shortLabel: "ATR%",
    description: "ATR as percentage of price — normalized volatility for cross-asset comparison.",
    category: "volatility",
    placement: "card",
    capabilities: ["group_table", "group_card", "detail_card", "detail_stats"],
    defaults: ["group_table", "detail_card"],
    fields: ["atr_pct"],
    sortableFields: ["atr_pct"],
    series: [
      {
        field: "atr_pct",
        label: "ATR%",
        color: "#f97316",
        lineWidth: 2,
      },
    ],
    decimals: 2,
    suffix: "%",
    holdingSummary: { label: "ATR%", field: "atr_pct", format: "numeric" },
  },
  {
    id: "adx",
    label: "ADX (14)",
    shortLabel: "ADX",
    description: "Trend strength regardless of direction. Above 25 = strong trend, below 20 = no trend.",
    category: "volatility",
    placement: "card",
    capabilities: ["group_table", "group_card", "detail_card", "detail_stats"],
    defaults: ["group_table", "detail_card"],
    fields: ["adx", "plus_di", "minus_di"],
    sortableFields: ["adx"],
    series: [
      {
        field: "adx",
        label: "ADX",
        color: "#06b6d4",
        lineWidth: 2,
        thresholdColors: [
          { condition: "gte", value: 25, className: "text-emerald-500" },
          { condition: "lt", value: 20, className: "text-zinc-400" },
        ],
      },
      { field: "plus_di", label: "+DI", color: "#22c55e", lineWidth: 1 },
      { field: "minus_di", label: "-DI", color: "#ef4444", lineWidth: 1 },
    ],
    decimals: 1,
    chartConfig: {
      lines: [
        { value: 25, color: "rgba(34, 197, 94, 0.4)" },
        { value: 20, color: "rgba(161, 161, 170, 0.3)" },
      ],
      range: { min: 0, max: 60 },
    },
    holdingSummary: {
      label: "ADX",
      field: "adx_trend",
      format: "string_map",
      colorMap: { strong: "text-emerald-500", weak: "text-yellow-500", absent: "text-zinc-400" },
    },
  },
  {
    id: "volume",
    label: "Volume",
    shortLabel: "Vol",
    description: "Today's trading volume and 20-day average.",
    category: "market_data",
    placement: "card",
    capabilities: ["group_table", "detail_stats"],
    defaults: ["group_table", "detail_stats"],
    fields: ["volume", "avg_volume"],
    sortableFields: ["volume", "avg_volume"],
    series: [],
    decimals: 0,
    compactFormat: true,
  },

  // ── Fundamentals ──────────────────────────────────────────────────────

  {
    id: "forward_pe",
    label: "Forward P/E",
    shortLabel: "Fwd P/E",
    description: "Price ÷ estimated next-12-month EPS. <10 cheap, 10–20 fair, 20–35 growth premium, >35 expensive.",
    category: "fundamentals",
    placement: "card",
    capabilities: ["group_table", "group_card", "detail_card", "detail_stats"],
    defaults: ["group_table", "detail_card"],
    fields: ["forward_pe"],
    sortableFields: ["forward_pe"],
    series: [
      {
        field: "forward_pe",
        label: "Fwd P/E",
        color: "#6366f1",
        thresholdColors: [
          { condition: "gt", value: 35, className: "text-red-500" },
          { condition: "gt", value: 20, className: "text-yellow-500" },
          { condition: "lt", value: 10, className: "text-emerald-500" },
        ],
      },
    ],
    decimals: 1,
    holdingSummary: { label: "Fwd P/E", field: "forward_pe", format: "numeric" },
  },
  {
    id: "peg_ratio",
    label: "PEG Ratio",
    shortLabel: "PEG",
    description: "Forward P/E ÷ earnings growth rate. <1 cheap relative to growth, 1 fairly valued, >2 expensive.",
    category: "fundamentals",
    placement: "card",
    capabilities: ["group_table", "group_card", "detail_card", "detail_stats"],
    defaults: ["group_table", "detail_card"],
    fields: ["peg_ratio"],
    sortableFields: ["peg_ratio"],
    series: [
      {
        field: "peg_ratio",
        label: "PEG",
        color: "#8b5cf6",
        thresholdColors: [
          { condition: "gt", value: 2, className: "text-red-500" },
          { condition: "lt", value: 1, className: "text-emerald-500" },
        ],
      },
    ],
    decimals: 2,
    holdingSummary: { label: "PEG", field: "peg_ratio", format: "numeric" },
  },
  {
    id: "roe",
    label: "ROE",
    shortLabel: "ROE",
    description: "Return on Equity — net income ÷ shareholder equity. >25% excellent, 15–25% strong, <10% mediocre.",
    category: "fundamentals",
    placement: "card",
    capabilities: ["group_table", "group_card", "detail_card", "detail_stats"],
    defaults: ["group_table", "detail_card"],
    fields: ["roe"],
    sortableFields: ["roe"],
    series: [
      {
        field: "roe",
        label: "ROE",
        color: "#0ea5e9",
        thresholdColors: [
          { condition: "gt", value: 25, className: "text-emerald-500" },
          { condition: "gt", value: 15, className: "text-teal-500" },
          { condition: "lt", value: 10, className: "text-red-500" },
        ],
      },
    ],
    decimals: 1,
    suffix: "%",
    holdingSummary: { label: "ROE", field: "roe", format: "numeric" },
  },
  {
    id: "ev_ebitda",
    label: "EV/EBITDA",
    shortLabel: "EV/EBITDA",
    description: "Enterprise value ÷ EBITDA. Best cross-border valuation metric. <8 cheap, 8–15 fair, >25 expensive.",
    category: "fundamentals",
    placement: "card",
    capabilities: ["group_table", "group_card", "detail_card", "detail_stats"],
    defaults: ["group_table", "detail_card"],
    fields: ["ev_ebitda"],
    sortableFields: ["ev_ebitda"],
    series: [
      {
        field: "ev_ebitda",
        label: "EV/EBITDA",
        color: "#14b8a6",
        thresholdColors: [
          { condition: "gt", value: 25, className: "text-red-500" },
          { condition: "gt", value: 15, className: "text-yellow-500" },
          { condition: "lt", value: 8, className: "text-emerald-500" },
        ],
      },
    ],
    decimals: 1,
    holdingSummary: { label: "EV/EBITDA", field: "ev_ebitda", format: "numeric" },
  },
  {
    id: "revenue_growth",
    label: "Revenue Growth",
    shortLabel: "Rev Gr",
    description: "Year-over-year revenue growth. >25% high growth, 10–25% solid, <0% shrinking.",
    category: "fundamentals",
    placement: "card",
    capabilities: ["group_table", "group_card", "detail_card", "detail_stats"],
    defaults: ["group_table", "detail_card"],
    fields: ["revenue_growth"],
    sortableFields: ["revenue_growth"],
    series: [
      {
        field: "revenue_growth",
        label: "Rev Growth",
        color: "#22c55e",
        thresholdColors: [
          { condition: "gt", value: 25, className: "text-emerald-500" },
          { condition: "gt", value: 10, className: "text-teal-500" },
          { condition: "lt", value: 0, className: "text-red-500" },
        ],
      },
    ],
    decimals: 1,
    suffix: "%",
    holdingSummary: { label: "Rev Gr", field: "revenue_growth", format: "numeric" },
  },
]
